# Generated by Django 3.2 on 2023-05-24 15:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Категория услуг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+7 111 222 33 44', max_length=128, region=None, unique=True, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название салона')),
                ('image', models.ImageField(db_index=True, upload_to='', verbose_name='Изображение')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='адрес')),
                ('work_time', models.CharField(default='с 10:00 до 20:00 без выходных', max_length=100, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж работы')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='service.salon', verbose_name='Салон')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='service.category', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название услуги')),
                ('descriptions', models.TextField(blank=True, db_index=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_hour', models.CharField(blank=True, choices=[('10:00', '10:00'), ('10:30', '10:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('18:30', '18:30'), ('19:00', '19:00')], max_length=20, verbose_name='Время записи')),
                ('order_day', models.DateField(null=True, verbose_name='Дата')),
                ('payment_method', models.CharField(blank=True, choices=[('cashless', 'Безналичный'), ('cash', 'Наличные')], db_index=True, max_length=12, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(choices=[('paid', 'Оплачен'), ('not_paid', 'Не оплачен')], db_index=True, default='not_paid', max_length=10, verbose_name='Статус оплаты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.client', verbose_name='Клиент')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.service', verbose_name='Услуга')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.salon', verbose_name='Салон')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
