# Generated by Django 3.2 on 2023-05-26 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(choices=[(datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30')], verbose_name='Начало')),
                ('end_time', models.TimeField(editable=False, verbose_name='Конец')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_working', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('daytime', models.CharField(blank=True, choices=[('M', 'Утро'), ('L', 'Обед'), ('E', 'Вечер')], db_index=True, max_length=1, verbose_name='Время суток')),
                ('specialist', models.ManyToManyField(related_name='appointments', to='service.Specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Временной период',
                'verbose_name_plural': 'Временные периоды',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_hour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='service.timeslot', verbose_name='Время приема'),
        ),
    ]
