# Generated by Django 3.2 on 2023-05-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_day',
        ),
    ]
