# Generated by Django 3.2 on 2023-05-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20230524_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='descriptions',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
