# Generated by Django 3.2 on 2023-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20230524_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='reviews_qty',
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
