# Generated by Django 3.2 on 2023-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20230524_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='order_day',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_hour',
            field=models.CharField(blank=True, choices=[('10:00', '10:00'), ('10:30', '10:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('18:30', '18:30'), ('19:00', '19:00')], max_length=20, verbose_name='Время записи'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
